name: 'Scala Steward Github Action'
author: alejandrohdezma
description: '🤖 A bot that helps you keeping your Scala projects up-to-date '
branding:
  icon:  arrow-up-circle
  color: red

inputs:
  repos-file:
    description: 'Path to a file containing the list of repositories to update in markdown format (- owner/repo)'
    required: false
  github-repository:
    description: 'Repository to update. The current repository will be used by default'
    required: false
  github-token:
    description: 'Github Personal Access Token with permission to create branches on repo'
    required: true
  author-email:
    description: Author email address to use in commits
    required: false
  author-name:
    description: Author name to use in commits
    required: false
  scala-steward-version:
    description: 'Scala Steward version to use'
    default: '0.5.0-385-e5e4789c-SNAPSHOT'
    required: false
  ignore-opts-files:
    description: 'Whether to ignore "opts" files (such as `.jvmopts` or `.sbtopts`) when found on repositories or not'
    default: 'true'
    required: false
  sign-commits:
    description: 'Whether to sign commits or not'
    default: 'false'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
